#!/usr/bin/sh

sxhkd &

bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

source ~/.zshrc
feh --bg-fill ~/Downloads/img/wallpaper.jpg
$HOME/.config/polybar/launch.sh
$HOME/.config/picom/picom-launch.sh

#Successfully installed siji.pcf -> /home/ntritran999/.fonts
#Add the following snippet in your custom startup script that gets executed during xlogin:

	xset +fp /home/ntritran999/.fonts
	xset fp rehash
	
setxkbmap -option grp:alt_shift_toggle us,vn &
